version: 2

models:
  - name: stg_orders
    description: "Stagingmodell för Superstore orderdata"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
